import "~/styles/globals.css";

import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import ScrollProgressBar from "~/components/ScrollProgressBar";

import { type Metadata } from "next";
import { Bricolage_Grotesque, Righteous } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const righteous = Righteous({
  subsets: ["latin"],
  variable: "--font-righteous",
  weight: ["400"],
});
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${bricolage.variable} ${righteous.variable}`}
      suppressHydrationWarning
    >
      <body className="font-body bg-background">
        <ScrollProgressBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
